In [4]:
import numpy as np

In [9]:
a = np.array([[1, 2, 1],[1,2,5]])
print('a= 'a)
b = np.array([[1, 2, 3],[1,2,2]])
print('b= 'b)

[[1 2 1]
 [1 2 5]]
[[1 2 3]
 [1 2 2]]


In [14]:
c=a+b
d=a*b
print('a+b= \n',c)
print('a*b= \n',d)

a+b= 
 [[2 4 4]
 [2 4 7]]
a*b= 
 [[ 1  4  3]
 [ 1  4 10]]


In [19]:
def chuyen_vi(mt):
    kq= print(mt.transpose())
    return kq

In [20]:
chuyen_vi(a)

[[1 1]
 [2 2]
 [1 5]]


In [21]:
chuyen_vi(b)

[[1 1]
 [2 2]
 [3 2]]
